# https://taskfile.dev

version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  default:
    
    cmds:
      - npm install -g youtube-playlist-markdown-cli
      - sh youtube_playlist_md.sh
      - python3 feedly_to_markdown.py ./FeedlySavedForLater1701691966152.json my-playlist-reinvent-2023.md
      - git add .
      - git commit -m 'update'
      - git push
    silent: true

  awsevent:
    desc: AWS Event
    cmds:
      - ym -c UCdoadna9HFHsxXWhafhNvKw
