# https://taskfile.dev

version: '3'

dotenv: ['.env', '{{.ENV}}/.env.', '{{.HOME}}/.env']

tasks:
  build:
    cmds:
      - python youtube_extractor.py extract --skip-videos --skip-transcript
      - python youtube_extractor.py generate-readme
      - git add .
      - git commit -m 'update'
      - git push
    silent: true



  python:
    cmds:
      - python youtube-playlist-markdown.py --playlist=PL2yQDdvlhXf8iyzg7ziZI924PxC8a8M-U


  venv:
    desc: Create local python virtual env
    cmds:
      - rm -rf .venv/ || true
      - python3 -m venv 3.11.0 .venv
      - .venv/bin/python3 -m pip install --upgrade --quiet pip
      - .venv/bin/pip3 install --quiet --requirement requirements.txt
    sources:
      - requirements.txt
    generates:
      - .venv/bin/activate